# Generated by Django 5.2.8 on 2025-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('estimated_time', models.IntegerField(help_text='Time in minutes')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
