# Generated by Django 5.2.8 on 2025-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('topics', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
